### ISSUE TITLE
packer directory

### ISSUE THREAD

**Issue by brucellino** [EGI-FCTF/fedcloud-userinterface#7]
The README says there's a packer configuration file but I don't see it - where is it ?

**Comment by enolfc** [comment]
It's in EGI-FCTF/VMI-endorsement repo:

https://github.com/EGI-FCTF/VMI-endorsement/blob/master/ubuntu/fedcloud-userinterface.json

I'm open to suggestions on how to make this better managed.

Also would like to get this into CD: push in the repo, build new image, push to AppDB...

**Comment by enolfc** [comment]
This issue was moved to https://community.egi.eu/t/packer-directory/72
